### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by 467754239** [kakwa/dnscherry#2]
![image](https://cloud.githubusercontent.com/assets/11746057/24321530/9c41b7aa-1189-11e7-8f19-4adeef688d03.png)

why problem

**Comment by kakwa** [comment]
Because you need some configuration in dnscherry and in the DNS zone on the DNS server. Specially the TSIG KEY.

The documentation provides an example of configuration using bind: 
http://dnscherry.readthedocs.io/en/latest/deploy.html
